version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: nitsrpidb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nitsrpi
    ports:
      - "5432:5432"
    networks:
      - nitsrpi-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4-NIT
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - nitsrpi-network
    restart: unless-stopped

networks:
  nitsrpi-network:
    driver: bridge
