# Configurações Customizadas do Sistema
file:
  upload-dir: ./uploads

# Configurações do Spring Framework
spring:
  application:
    name: srpi

  # Banco de Dados PostgreSQL
  datasource:
#    url: jdbc:postgresql://localhost:5432/nitsrpi
    url: jdbc:postgresql://postgres:5432/nitsrpi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Configurações de JPA e Hibernate
  jpa:
    show-sql: true
    hibernate:
      # Como você está usando 'none', lembre-se de criar as tabelas manualmente no banco
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração de Upload de Arquivos
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # Tamanho máximo de CADA arquivo
      max-request-size: 10MB   # Tamanho máximo da REQUISIÇÃO total

# Configuração de Logs (Opcional, ajuda a debugar erros de banco)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
